### ISSUE TITLE
Fails using token for forked repo

### ISSUE THREAD

**Issue by chemelli74** [grafana/pr-labeler-action#49]
Recently we are experiencing the issue shown by this run: https://github.com/rokam/midea-local/actions/runs/11203313741/job/31140493729

Can you help identifying the issue ?

CC @rokam (https://github.com/rokam/midea-local/issues/314)

**Comment by chemelli74** [comment]
Any kind feedback ?

**Comment by chemelli74** [comment]
A kind reminder for a feedback

**Comment by abannachGrafana** [comment]
👋 Sorry for the missed notifications. Looks like you have a successful run at least once using a PAT. We've been successfully using the action with the `GITHUB_TOKEN` internally, but you do need to elevate the privileges a bit.

here's and example as a full workflow file.

```yaml
name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr-title:
    runs-on: ubuntu-x64
    name: Check PR Title
    steps:
      - name: Check PR Title
        uses: agenthunt/conventional-commit-checker-action@9e552d650d0e205553ec7792d447929fc78e012b # v2.0.0
        with:
          pr-title-regex: "^(build|chore|ci|docs|feat|fix|perf|refactor|style|test)(\\(.+\\))?(!)?:\\s.*"
          pr-body-regex: ".*" # We don't really care what the PR body description contains, just the title

  label:
    permissions:
      contents: read
      issues: read
      pull-requests: write
    if: github.actor != 'dependabot[bot]' # dependabot adds it's own labels
    runs-on: ubuntu-x64
    name: Update PR Labels
    needs: ['pr-title'] # Makes sure that the title follows conventional commits
    steps:
      - name: Label PR
        uses: grafana/pr-labeler-action@50737759cb150f5d312de1a45559027156db8bab # v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

```

You'll notice the label job depends on `pr-title` which we're using for labeling purposes. Just an extra little check to make sure it doesn't fail to map a label type.

Let me know if that works for you as well. Feel free to tweak or omit the pr-title job. Ultimately I believe the fix will be to add the

```
permissions:
  contents: read
  issues: read
  pull-requests: write
```

to your labeling job
